server:
  port: ${port:20105}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
spring:
  rabbitmq:
    addresses: 10.20.196.20:5672
    host: 10.20.196.20
    port: ${evo.rabbitmq.port}
    virtual-host: ${evo.rabbitmq.virtual-host}
    username: ${evo.rabbitmq.username}
    password: ${evo.rabbitmq.password}
  redis:
    cluster:
      nodes: 10.20.196.23:7001, 10.20.196.23:7002, 10.20.196.23:7003, 10.20.196.23:7004, 10.20.196.23:7005, 10.20.196.23:7006
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
  main:
    allow-bean-definition-overriding: true
evo:
  re
