server:
  port: ${port:20400}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
spring:
  datasource:
    url: ${evo.framework.datasource.url}
    username: ${evo.framework.datasource.username}
    password: ${evo.framework.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000 # 等待连接池分配连接的最大时长 30秒
      idle-timeout: 600000 # 连接闲置状态的最大时长 10分钟
      maximum-pool-size: 1 # 连接池中允许的最大连接数, 推荐的公式：((core_count * 2) + effective_spindle_count)
      max-lifetime: 1800000 # 连接的生命时长 30分钟, 建议设置比数据库超时时长少30秒
      # minimum-idle: 500 当空闲连接数超过minimumIdle，而且空闲时间超过idleTimeout，则会被移除。不建议设置此值，而是让HikariCP把连接池当做固定大小的处理，默认minimumIdle与maximumPoolSize一样。
      read-only: false # 连接只读数据库时配置为true, 保证安全
  rabbitmq:
    addresses: ${evo.rabbitmq.addresses}
    host: ${evo.rabbitmq.host}
    port: ${evo.rabbitmq.port}
    virtual-host: ${evo.rabbitmq.virtual-host}
    username: ${evo.rabbitmq.username}
    password: ${evo.rabbitmq.password}
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  type-aliases-package: com.github.framework.evo.controller.entity
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      select-strategy: ignored
evo-config:
  ribbon:
    ReadTimeout: 60000
evo:
  session:
    user-context:
      enabled: false
